### ISSUE TITLE
Can't open any video file

### ISSUE THREAD

**Issue by sed03** [kmcclive/tricycle#62] opened 2020-05-12 07:36 UTC
I'm trying version 2.3.0 on Windows 10 64-bit English and I can't open any video file. I have tried several mp4 and mkv files.

Invalid Source
The selected file could not be opened.

**Comment by kmcclive** [comment] 2020-05-23 17:05
Hi, @sed03. Thanks for letting me know.  I added some logging to the app and released a new version.  Would you mind installing it and giving it another try?  Here is a link:

https://github.com/kmcclive/tricycle/releases/download/release%2F2-4-0/Tricycle-Windows.msi

This likely won't fix the problem, but it may indicate what the problem is.  Here is what I'd like you to do:

1. Start the app
1. Go to Tools > Options
1. Select Advanced from the left navigation
1. Check the Trace Logging box
1. Restart the app
1. Try to open a few files
1. Close the app
1. Locate the log file in %localappdata%/Tricycle/Logs (you can type that in the Windows search box)
1. Attach the file to this issue (drag it to the comment box)

Thanks in advance.  Hopefully, we can get this sorted out without much trouble.

**Comment by sed03** [comment] 2020-05-24 08:30
The latest version doesn't start at all.  No error messages.

I have .NET Framework 4.8 installed.

**Comment by kmcclive** [comment] 2020-05-24 16:19
@sed03 That sounds like a bad installation. Can you uninstall it and then make sure that the directory where you installed it is completely gone? If it’s not, you should delete it. After that, try installing the new version.

**Comment by sed03** [comment] 2020-05-24 16:27
Log file from version 2.4.0

Still same error message.

`2020-05-24T16:22:30 Starting process: C:\Program Files\Tricycle\Assets\Tools\FFmpeg\ffprobe.exe -loglevel error -print_format json -show_format -show_streams -i "C:\Users\Stefan\Videos\2019-04-05 11-26-55.mp4"
2020-05-24T16:22:30 {
2020-05-24T16:22:30     "streams": [
2020-05-24T16:22:30         {
2020-05-24T16:22:30             "index": 0,
2020-05-24T16:22:30             "codec_name": "h264",
2020-05-24T16:22:30             "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
2020-05-24T16:22:30             "profile": "High",
2020-05-24T16:22:30             "codec_type": "video",
2020-05-24T16:22:30             "codec_time_base": "10233/614000",
2020-05-24T16:22:30             "codec_tag_string": "avc1",
2020-05-24T16:22:30             "codec_tag": "0x31637661",
2020-05-24T16:22:30             "width": 2560,
2020-05-24T16:22:30             "height": 1440,
2020-05-24T16:22:30             "coded_width": 2560,
2020-05-24T16:22:30             "coded_height": 1440,
2020-05-24T16:22:30             "has_b_frames": 1,
2020-05-24T16:22:30             "sample_aspect_ratio": "1:1",
2020-05-24T16:22:30             "display_aspect_ratio": "16:9",
2020-05-24T16:22:30             "pix_fmt": "yuv420p",
2020-05-24T16:22:30             "level": 50,
2020-05-24T16:22:30             "color_range": "tv",
2020-05-24T16:22:30             "color_space": "bt470bg",
2020-05-24T16:22:30             "color_transfer": "bt709",
2020-05-24T16:22:30             "color_primaries": "bt709",
2020-05-24T16:22:30             "chroma_location": "left",
2020-05-24T16:22:30             "refs": 1,
2020-05-24T16:22:30             "is_avc": "true",
2020-05-24T16:22:30             "nal_length_size": "4",
2020-05-24T16:22:30             "r_frame_rate": "30/1",
2020-05-24T16:22:30             "avg_frame_rate": "307000/10233",
2020-05-24T16:22:30             "time_base": "1/90000",
2020-05-24T16:22:30             "start_pts": 2970,
2020-05-24T16:22:30             "start_time": "0.033000",
2020-05-24T16:22:30             "duration_ts": 2762910,
2020-05-24T16:22:30             "duration": "30.699000",
2020-05-24T16:22:30             "bit_rate": "2421707",
2020-05-24T16:22:30             "bits_per_raw_sample": "8",
2020-05-24T16:22:30             "nb_frames": "921",
2020-05-24T16:22:30             "disposition": {
2020-05-24T16:22:30                 "default": 1,
2020-05-24T16:22:30                 "dub": 0,
2020-05-24T16:22:30                 "original": 0,
2020-05-24T16:22:30                 "comment": 0,
2020-05-24T16:22:30                 "lyrics": 0,
2020-05-24T16:22:30                 "karaoke": 0,
2020-05-24T16:22:30                 "forced": 0,
2020-05-24T16:22:30                 "hearing_impaired": 0,
2020-05-24T16:22:30                 "visual_impaired": 0,
2020-05-24T16:22:30                 "clean_effects": 0,
2020-05-24T16:22:30                 "attached_pic": 0,
2020-05-24T16:22:30                 "timed_thumbnails": 0
2020-05-24T16:22:30             },
2020-05-24T16:22:30             "tags": {
2020-05-24T16:22:30                 "language": "und",
2020-05-24T16:22:30                 "handler_name": "VideoHandler"
2020-05-24T16:22:30             }
2020-05-24T16:22:30         },
2020-05-24T16:22:30         {
2020-05-24T16:22:30             "index": 1,
2020-05-24T16:22:30             "codec_name": "aac",
2020-05-24T16:22:30             "codec_long_name": "AAC (Advanced Audio Coding)",
2020-05-24T16:22:30             "profile": "LC",
2020-05-24T16:22:30             "codec_type": "audio",
2020-05-24T16:22:30             "codec_time_base": "1/44100",
2020-05-24T16:22:30             "codec_tag_string": "mp4a",
2020-05-24T16:22:30             "codec_tag": "0x6134706d",
2020-05-24T16:22:30             "sample_fmt": "fltp",
2020-05-24T16:22:30             "sample_rate": "44100",
2020-05-24T16:22:30             "channels": 2,
2020-05-24T16:22:30             "channel_layout": "stereo",
2020-05-24T16:22:30             "bits_per_sample": 0,
2020-05-24T16:22:30             "r_frame_rate": "0/0",
2020-05-24T16:22:30             "avg_frame_rate": "0/0",
2020-05-24T16:22:30             "time_base": "1/44100",
2020-05-24T16:22:30             "start_pts": 1411,
2020-05-24T16:22:30             "start_time": "0.031995",
2020-05-24T16:22:30             "duration_ts": 1352679,
2020-05-24T16:22:30             "duration": "30.672993",
2020-05-24T16:22:30             "bit_rate": "160719",
2020-05-24T16:22:30             "max_bit_rate": "160719",
2020-05-24T16:22:30             "nb_frames": "1321",
2020-05-24T16:22:30             "disposition": {
2020-05-24T16:22:30                 "default": 1,
2020-05-24T16:22:30                 "dub": 0,
2020-05-24T16:22:30                 "original": 0,
2020-05-24T16:22:30                 "comment": 0,
2020-05-24T16:22:30                 "lyrics": 0,
2020-05-24T16:22:30                 "karaoke": 0,
2020-05-24T16:22:30                 "forced": 0,
2020-05-24T16:22:30                 "hearing_impaired": 0,
2020-05-24T16:22:30 
2020-05-24T16:22:30                 "visual_impaired": 0,
2020-05-24T16:22:30                 "clean_effects": 0,
2020-05-24T16:22:30                 "attached_pic": 0,
2020-05-24T16:22:30                 "timed_thumbnails": 0
2020-05-24T16:22:30             },
2020-05-24T16:22:30             "tags": {
2020-05-24T16:22:30                 "language": "und",
2020-05-24T16:22:30                 "handler_name": "SoundHandler"
2020-05-24T16:22:30             }
2020-05-24T16:22:30         }
2020-05-24T16:22:30     ],
2020-05-24T16:22:30     "format": {
2020-05-24T16:22:30         "filename": "C:\\Users\\Stefan\\Videos\\2019-04-05 11-26-55.mp4",
2020-05-24T16:22:30         "nb_streams": 2,
2020-05-24T16:22:30         "nb_programs": 0,
2020-05-24T16:22:30         "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
2020-05-24T16:22:30         "format_long_name": "QuickTime / MOV",
2020-05-24T16:22:30         "start_time": "0.031995",
2020-05-24T16:22:30         "duration": "30.699000",
2020-05-24T16:22:30         "size": "9954619",
2020-05-24T16:22:30         "bit_rate": "2594122",
2020-05-24T16:22:30         "probe_score": 100,
2020-05-24T16:22:30         "tags": {
2020-05-24T16:22:30             "major_brand": "isom",
2020-05-24T16:22:30             "minor_version": "512",
2020-05-24T16:22:30             "compatible_brands": "isomiso2avc1mp41",
2020-05-24T16:22:30             "encoder": "Lavf57.84.100"
2020-05-24T16:22:30         }
2020-05-24T16:22:30     }
2020-05-24T16:22:30 }
2020-05-24T16:22:30 
2020-05-24T16:23:49 Starting process: C:\Program Files\Tricycle\Assets\Tools\FFmpeg\ffprobe.exe -loglevel error -print_format json -show_format -show_streams -i "C:\Users\Stefan\Videos\totcity.mp4"
2020-05-24T16:23:49 {
2020-05-24T16:23:49     "streams": [
2020-05-24T16:23:49         {
2020-05-24T16:23:49             "index": 0,
2020-05-24T16:23:49             "codec_name": "h264",
2020-05-24T16:23:49             "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
2020-05-24T16:23:49             "profile": "High",
2020-05-24T16:23:49             "codec_type": "video",
2020-05-24T16:23:49             "codec_time_base": "3474133/208448000",
2020-05-24T16:23:49             "codec_tag_string": "avc1",
2020-05-24T16:23:49             "codec_tag": "0x31637661",
2020-05-24T16:23:49             "width": 1920,
2020-05-24T16:23:49             "height": 1080,
2020-05-24T16:23:49             "coded_width": 1920,
2020-05-24T16:23:49             "coded_height": 1088,
2020-05-24T16:23:49             "has_b_frames": 1,
2020-05-24T16:23:49             "sample_aspect_ratio": "1:1",
2020-05-24T16:23:49             "display_aspect_ratio": "16:9",
2020-05-24T16:23:49             "pix_fmt": "yuv420p",
2020-05-24T16:23:49             "level": 40,
2020-05-24T16:23:49             "color_range": "tv",
2020-05-24T16:23:49             "color_space": "bt470bg",
2020-05-24T16:23:49             "color_transfer": "bt709",
2020-05-24T16:23:49             "color_primaries": "bt709",
2020-05-24T16:23:49             "chroma_location": "left",
2020-05-24T16:23:49             "refs": 1,
2020-05-24T16:23:49             "is_avc": "true",
2020-05-24T16:23:49             "nal_length_size": "4",
2020-05-24T16:23:49             "r_frame_rate": "30/1",
2020-05-24T16:23:49             "avg_frame_rate": "104224000/3474133",
2020-05-24T16:23:49             "time_base": "1/90000",
2020-05-24T16:23:49             "start_pts": 2970,
2020-05-24T16:23:49             "start_time": "0.033000",
2020-05-24T16:23:49             "duration_ts": 625343940,
2020-05-24T16:23:49             "duration": "6948.266000",
2020-05-24T16:23:49             "bit_rate": "2497977",
2020-05-24T16:23:49             "bits_per_raw_sample": "8",
2020-05-24T16:23:49             "nb_frames": "208448",
2020-05-24T16:23:49             "disposition": {
2020-05-24T16:23:49                 "default": 1,
2020-05-24T16:23:49                 "dub": 0,
2020-05-24T16:23:49                 "original": 0,
2020-05-24T16:23:49                 "comment": 0,
2020-05-24T16:23:49                 "lyrics": 0,
2020-05-24T16:23:49                 "karaoke": 0,
2020-05-24T16:23:49                 "forced": 0,
2020-05-24T16:23:49                 "hearing_impaired": 0,
2020-05-24T16:23:49                 "visual_impaired": 0,
2020-05-24T16:23:49                 "clean_effects": 0,
2020-05-24T16:23:49                 "attached_pic": 0,
2020-05-24T16:23:49                 "timed_thumbnails": 0
2020-05-24T16:23:49             },
2020-05-24T16:23:49             "tags": {
2020-05-24T16:23:49                 "language": "und",
2020-05-24T16:23:49                 "handler_name": "VideoHandler"
2020-05-24T16:23:49             }
2020-05-24T16:23:49         },
2020-05-24T16:23:49         {
2020-05-24T16:23:49             "index": 1,
2020-05-24T16:23:49             "codec_name": "aac",
2020-05-24T16:23:49             "codec_long_name": "AAC (Advanced Audio Coding)",
2020-05-24T16:23:49             "profile": "LC",
2020-05-24T16:23:49             "codec_type": "audio",
2020-05-24T16:23:49             "codec_time_base": "1/44100",
2020-05-24T16:23:49             "codec_tag_string": "mp4a",
2020-05-24T16:23:49             "codec_tag": "0x6134706d",
2020-05-24T16:23:49             "sample_fmt": "fltp",
2020-05-24T16:23:49             "sample_rate": "44100",
2020-05-24T16:23:49             "channels": 2,
2020-05-24T16:23:49             "channel_layout": "stereo",
2020-05-24T16:23:49             "bits_per_sample": 0,
2020-05-24T16:23:49             "r_frame_rate": "0/0",
2020-05-24T16:23:49             "avg_frame_rate": "0/0",
2020-05-24T16:23:49             "time_base": "1/44100",
2020-05-24T16:23:49             "start_pts": 1411,
2020-05-24T16:23:49             "start_time": "0.031995",
2020-05-24T16:23:49             "duration_ts": 306417649,
2020-05-24T16:23:49             "duration": "6948.246009",
2020-05-24T16:23:49             "bit_rate": "160810",
2020-05-24T16:23:49             "max_bit_rate": "160810",
2020-05-24T16:23:49             "nb_frames": "299236",
2020-05-24T16:23:49             "disposition": {
2020-05-24T16:23:49                 "default": 1,
2020-05-24T16:23:49                 "dub": 0,
2020-05-24T16:23:49                 "original": 0,
2020-05-24T16:23:49                 "comment": 0,
2020-05-24T16:23:49                 "lyrics": 0,
2020-05-24T16:23:49                 "karaoke": 0,
2020-05-24T16:23:49                 "forced": 0,
2020-05-24T16:23:49 
2020-05-24T16:23:49                 "hearing_impaired": 0,
2020-05-24T16:23:49                 "visual_impaired": 0,
2020-05-24T16:23:49                 "clean_effects": 0,
2020-05-24T16:23:49                 "attached_pic": 0,
2020-05-24T16:23:49                 "timed_thumbnails": 0
2020-05-24T16:23:49             },
2020-05-24T16:23:49             "tags": {
2020-05-24T16:23:49                 "language": "und",
2020-05-24T16:23:49                 "handler_name": "SoundHandler"
2020-05-24T16:23:49             }
2020-05-24T16:23:49         }
2020-05-24T16:23:49     ],
2020-05-24T16:23:49     "format": {
2020-05-24T16:23:49         "filename": "C:\\Users\\Stefan\\Videos\\totcity.mp4",
2020-05-24T16:23:49         "nb_streams": 2,
2020-05-24T16:23:49         "nb_programs": 0,
2020-05-24T16:23:49         "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
2020-05-24T16:23:49         "format_long_name": "QuickTime / MOV",
2020-05-24T16:23:49         "start_time": "0.031995",
2020-05-24T16:23:49         "duration": "6948.266000",
2020-05-24T16:23:49         "size": "2319214590",
2020-05-24T16:23:49         "bit_rate": "2670265",
2020-05-24T16:23:49         "probe_score": 100,
2020-05-24T16:23:49         "tags": {
2020-05-24T16:23:49             "major_brand": "isom",
2020-05-24T16:23:49             "minor_version": "512",
2020-05-24T16:23:49             "compatible_brands": "isomiso2avc1mp41",
2020-05-24T16:23:49             "encoder": "Lavf57.84.100"
2020-05-24T16:23:49         }
2020-05-24T16:23:49     }
2020-05-24T16:23:49 }
2020-05-24T16:23:49 
2020-05-24T16:24:03 Starting process: C:\Program Files\Tricycle\Assets\Tools\FFmpeg\ffprobe.exe -loglevel error -print_format json -show_format -show_streams -i "D:\Downloads\1.mp4"
2020-05-24T16:24:03 {
2020-05-24T16:24:03     "streams": [
2020-05-24T16:24:03         {
2020-05-24T16:24:03             "index": 0,
2020-05-24T16:24:03             "codec_name": "mpeg4",
2020-05-24T16:24:03             "codec_long_name": "MPEG-4 part 2",
2020-05-24T16:24:03             "profile": "Simple Profile",
2020-05-24T16:24:03             "codec_type": "video",
2020-05-24T16:24:03             "codec_time_base": "1/25",
2020-05-24T16:24:03             "codec_tag_string": "mp4v",
2020-05-24T16:24:03             "codec_tag": "0x7634706d",
2020-05-24T16:24:03             "width": 480,
2020-05-24T16:24:03             "height": 360,
2020-05-24T16:24:03             "coded_width": 480,
2020-05-24T16:24:03             "coded_height": 360,
2020-05-24T16:24:03             "has_b_frames": 0,
2020-05-24T16:24:03             "sample_aspect_ratio": "1:1",
2020-05-24T16:24:03             "display_aspect_ratio": "4:3",
2020-05-24T16:24:03             "pix_fmt": "yuv420p",
2020-05-24T16:24:03             "level": 1,
2020-05-24T16:24:03             "chroma_location": "left",
2020-05-24T16:24:03             "refs": 1,
2020-05-24T16:24:03             "quarter_sample": "false",
2020-05-24T16:24:03             "divx_packed": "false",
2020-05-24T16:24:03             "r_frame_rate": "25/1",
2020-05-24T16:24:03             "avg_frame_rate": "25/1",
2020-05-24T16:24:03             "time_base": "1/25",
2020-05-24T16:24:03             "start_pts": 0,
2020-05-24T16:24:03             "start_time": "0.000000",
2020-05-24T16:24:03             "duration_ts": 2419,
2020-05-24T16:24:03             "duration": "96.760000",
2020-05-24T16:24:03             "bit_rate": "514169",
2020-05-24T16:24:03             "max_bit_rate": "514169",
2020-05-24T16:24:03             "nb_frames": "2419",
2020-05-24T16:24:03             "disposition": {
2020-05-24T16:24:03                 "default": 1,
2020-05-24T16:24:03                 "dub": 0,
2020-05-24T16:24:03                 "original": 0,
2020-05-24T16:24:03                 "comment": 0,
2020-05-24T16:24:03                 "lyrics": 0,
2020-05-24T16:24:03                 "karaoke": 0,
2020-05-24T16:24:03                 "forced": 0,
2020-05-24T16:24:03                 "hearing_impaired": 0,
2020-05-24T16:24:03                 "visual_impaired": 0,
2020-05-24T16:24:03                 "clean_effects": 0,
2020-05-24T16:24:03                 "attached_pic": 0,
2020-05-24T16:24:03                 "timed_thumbnails": 0
2020-05-24T16:24:03             },
2020-05-24T16:24:03             "tags": {
2020-05-24T16:24:03                 "language": "und",
2020-05-24T16:24:03                 "handler_name": "VideoHandler"
2020-05-24T16:24:03             }
2020-05-24T16:24:03         },
2020-05-24T16:24:03         {
2020-05-24T16:24:03             "index": 1,
2020-05-24T16:24:03             "codec_name": "aac",
2020-05-24T16:24:03             "codec_long_name": "AAC (Advanced Audio Coding)",
2020-05-24T16:24:03             "profile": "LC",
2020-05-24T16:24:03             "codec_type": "audio",
2020-05-24T16:24:03             "codec_time_base": "1/44100",
2020-05-24T16:24:03             "codec_tag_string": "mp4a",
2020-05-24T16:24:03             "codec_tag": "0x6134706d",
2020-05-24T16:24:03             "sample_fmt": "fltp",
2020-05-24T16:24:03             "sample_rate": "44100",
2020-05-24T16:24:03             "channels": 1,
2020-05-24T16:24:03             "channel_layout": "mono",
2020-05-24T16:24:03             "bits_per_sample": 0,
2020-05-24T16:24:03             "r_frame_rate": "0/0",
2020-05-24T16:24:03             "avg_frame_rate": "0/0",
2020-05-24T16:24:03             "time_base": "1/44100",
2020-05-24T16:24:03             "start_pts": 0,
2020-05-24T16:24:03             "start_time": "0.000000",
2020-05-24T16:24:03             "duration_ts": 4271104,
2020-05-24T16:24:03             "duration": "96.850431",
2020-05-24T16:24:03             "bit_rate": "63892",
2020-05-24T16:24:03             "max_bit_rate": "64000",
2020-05-24T16:24:03             "nb_frames": "4171",
2020-05-24T16:24:03             "disposition": {
2020-05-24T16:24:03                 "default": 1,
2020-05-24T16:24:03                 "dub": 0,
2020-05-24T16:24:03                 "original": 0,
2020-05-24T16:24:03                 "comment": 0,
2020-05-24T16:24:03                 "lyrics": 0,
2020-05-24T16:24:03                 "karaoke": 0,
2020-05-24T16:24:03                 "forced": 0,
2020-05-24T16:24:03                 "hearing_impaired": 0,
2020-05-24T16:24:03                 "visual_impaired": 0,
2020-05-24T16:24:03                 "clean_effects": 0,
2020-05-24T16:24:03                 "attached_pic": 0,
2020-05-24T16:24:03                 "timed_thumbnails": 0
2020-05-24T16:24:03             },
2020-05-24T16:24:03             "tags": {
2020-05-24T16:24:03                 "language": "und",
2020-05-24T16:24:03                 "handler_name": "SoundHandler"
2020-05-24T16:24:03             }
2020-05-24T16:24:03         }
2020-05-24T16:24:03     ],
2020-05-24T16:24:03     "format": {
2020-05-24T16:24:03         "filename": "D:\\Downloads\\1.mp4",
2020-05-24T16:24:03         "nb_streams": 2,
2020-05-24T16:24:03         "nb_programs": 0,
2020-05-24T16:24:03         "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
2020-05-24T16:24:03         "format_long_name": "QuickTime / MOV",
2020-05-24T16:24:03         "start_time": "0.000000",
2020-05-24T16:24:03         "duration": "96.851000",
2020-05-24T16:24:03         "size": "7056405",
2020-05-24T16:24:03         "bit_rate": "582866",
2020-05-24T16:24:03         "probe_score": 100,
2020-05-24T16:24:03         "tags": {
2020-05-24T16:24:03             "major_brand": "isom",
2020-05-24T16:24:03             "minor_version": "512",
2020-05-24T16:24:03             "compatible_brands": "isomiso2mp41",
2020-05-24T16:24:03             "encoder": "Lavf53.32.100"
2020-05-24T16:24:03         }
2020-05-24T16:24:03     }
2020-05-24T16:24:03 }
2020-05-24T16:24:03 
2020-05-24T16:24:03 
`

**Comment by sed03** [comment] 2020-05-24 16:27
Attaching log file also.

**Comment by kmcclive** [comment] 2020-05-29 02:26
@sed03 I didn't find anything in the log that indicated a problem.  For that reason, I released another version that added even more logging.  Would you mind installing it and performing the same steps as before?  By the way, I also made a small change to the Windows installer that I hope will prevent bad installations like you experienced.  Please let me know if you have trouble with that again.  Thanks!

https://github.com/kmcclive/tricycle/releases/download/v2.4.1/Tricycle-Windows.msi

**Comment by sed03** [comment] 2020-05-29 07:29
Still same error. And I can't see anything new in the error log.
[tricycle-2020-05-29.log](https://github.com/kmcclive/tricycle/files/4700253/tricycle-2020-05-29.log)

**Comment by kmcclive** [comment] 2020-05-29 13:31
@sed03 While I am glad to hear that the app didn't crash by installing over the old version, It doesn't look like you are using the new version.  The new version adds more information to most log messages.  I'd ask you to check which version you are using in the About window, but that won't indicate that all the files updated correctly.  Could you try doing a full uninstall as you did before?  I'm sorry about that; I don't know what is wrong with the installer.  You will know that it is the new version because many of the log messages will include either "[stdout]" or "[stderr]" just after the timestamp.

**Comment by sed03** [comment] 2020-05-29 13:35
It said version 2.4.1 in the about box. But uninstalled and installed again and now stdout is in the log file.
[tricycle-2020-05-29.log](https://github.com/kmcclive/tricycle/files/4702052/tricycle-2020-05-29.log)

**Comment by kmcclive** [comment] 2020-05-30 18:11
@sed03 I have a theory about what the problem is, but I would appreciate if you would give me some information about your system so that I can confirm it.  There are two ways you can do that.  If you have PowerShell installed, you can run the command ` Get-Culture | Select -ExpandProperty NumberFormat` and paste the output in a comment to this issue.  Otherwise, you can perform the following steps:
1. From the Start menu, search for "intl.cpl" and hit Enter
1. In the Region window, click _Additional Settings..._
1. In the Customize Format window, ensure that the Numbers tab is selected
1. Take a screenshot of the window
1. Attach the screenshot to this issue

**Comment by sed03** [comment] 2020-05-30 18:18
`CurrencyDecimalDigits    : 2
CurrencyDecimalSeparator : .
IsReadOnly               : False
CurrencyGroupSizes       : {3}
NumberGroupSizes         : {3}
PercentGroupSizes        : {3}
CurrencyGroupSeparator   : ,
CurrencySymbol           : $
NaNSymbol                : NaN
CurrencyNegativePattern  : 0
NumberNegativePattern    : 1
PercentPositivePattern   : 1
PercentNegativePattern   : 1
NegativeInfinitySymbol   : -∞
NegativeSign             : -
NumberDecimalDigits      : 2
NumberDecimalSeparator   : .
NumberGroupSeparator     : ,
CurrencyPositivePattern  : 0
PositiveInfinitySymbol   : ∞
PositiveSign             : +
PercentDecimalDigits     : 2
PercentDecimalSeparator  : .
PercentGroupSeparator    : ,
PercentSymbol            : %
PerMilleSymbol           : ‰
NativeDigits             : {0, 1, 2, 3...}
DigitSubstitution        : None`

Windows is english but with swedish numberformat.

**Comment by kmcclive** [comment] 2020-05-30 18:41
@sed03 When you say you use the Swedish number format, do you mean that there is a comma for the decimal separator? I’m just a little confused because that is not indicated in the output you sent me. I may have just given you the wrong command though. I have been wrong before. 😂

**Comment by sed03** [comment] 2020-05-30 18:46
![numberformat](https://user-images.githubusercontent.com/264314/83336791-9d98b600-a2b6-11ea-8a0e-fa3b32623fe2.png)

**Comment by kmcclive** [comment] 2020-05-30 20:29
@sed03 I think I fixed the problem, assuming my theory is correct.  Can you install the latest version and give it a try?  You may want to do a clean install to be sure you are using the latest code.  If it does work, you may also want to disable trace logging.  Those log files can fill up pretty fast when you are transcoding.

https://github.com/kmcclive/tricycle/releases/download/v2.4.2/Tricycle-Windows.msi

**Comment by sed03** [comment] 2020-05-30 22:14
I can open files but not transcode/convert anything.
![transcode](https://user-images.githubusercontent.com/264314/83340018-bcf20c00-a2d3-11ea-8c2f-60e4f0302d31.png)

**Comment by kmcclive** [comment] 2020-05-30 22:50
@sed03 Well, I guess that’s progress. Can you try it with logging on and attach the log file?

**Comment by sed03** [comment] 2020-05-31 06:34
Okey
[tricycle-2020-05-31.log](https://github.com/kmcclive/tricycle/files/4707194/tricycle-2020-05-31.log)

**Comment by kmcclive** [comment] 2020-06-01 21:51
@sed03 Since the original problem was fixed, I am closing this issue.  I have created #79 to track the new problem.

**Closed by kmcclive** 2020-06-01 21:51 UTC
Labels: bug, windows
