### ISSUE TITLE
Tricycle closing when scanning files

### ISSUE THREAD

**Issue by Johntony90** [kmcclive/tricycle#89] opened 2020-12-08 18:51 UTC
Firstly, just wanted to say thank you for this tool! It has helped reduce my media library size considerably, and is making it viable to now keep more movies in 4K format than before.

Now to my problem. As the title suggests, having some issues when trying to convert some videos. Interestingly, not all, so I presume there is something about the file that Tricycle doesn't like, but can't tell what.

[tricycle-2020-12-08.log](https://github.com/kmcclive/tricycle/files/5661195/tricycle-2020-12-08.log)

Attached is a log from one I know fails, so just ran it now to get the log file. I can provide more for different files if needed.
It doesn't have anything to do with size, as I have just ran some 120GB files through with no issues.

Running v2.4.3 on Windows 10 Pro, version 20H2, OS Build 19042.630. Using an i7-8700 with 32GB of RAM.

If you need any more information, please let me know.

Thanks in advance.

**Comment by treneth333** [comment] 2020-12-17 00:44
I would check the permissions and file attributes of the MP4 it could be set as read only not allowing tricycle to modify it.

Just for a start, if it's not that I've got some other ideas to troubleshoot it.

Hope this helps 😁

**Comment by Johntony90** [comment] 2020-12-21 18:10
Hi @treneth333 

Thanks for the suggestion - I'm converting from MKV to MP4, but can see no suggestion that the MKV is set as "Read Only" (the check box is unmarked on the first page of properties).

I'd be open to hear any other suggestions. As mentioned, it seems to be an issue with specific files, so don't know if there is some sort of property in them that it cannot read.

Thanks

**Comment by kmcclive** [comment] 2020-12-31 16:18
@Johntony90 What do you mean by "closing when scanning"?  Does the app crash or does it prohibit you from transcoding the file you selected?

**Comment by Johntony90** [comment] 2021-01-16 17:17
It crashes. No process running in Task Manager after either.

**Comment by kmcclive** [comment] 2021-01-28 23:05
@Johntony90 I was able to reproduce the problem.  Thanks so much for providing the log.  I appear to have fixed it from my testing.  That will fix will go out soon in the next release.  FYI, that video will not be identified as HDR by Tricycle.  It has a wide color gamut, but is missing the HDR metadata.  To be honest, I don't know how Tricycle will handle that when it transcodes it.  I haven't tested that, but I'd be interested in hearing what you find.

**Comment by kmcclive** [comment] 2021-02-03 00:30
@Johntony90 I released a new version of Tricycle.  Could you try scanning that file again?  As I mentioned in my last message, I think this will at least prevent Tricycle from crashing.  You may need to uninstall Tricycle and reinstall it again for the changes to take effect. This is a known issue with the Windows installer, which I have an issue open for.  Thanks!

https://github.com/kmcclive/tricycle/releases/download/v2.5.0/Tricycle-Windows.msi

**Comment by kmcclive** [comment] 2021-03-08 23:54
Closing due to inactivity

**Closed by kmcclive** 2021-03-08 23:54 UTC
